### ISSUE TITLE
[BUG]: Support solution configuration names other than just Debug and Release

### ISSUE THREAD

**Issue by icnocop** [wgnf/SlnParser#21]
### Description of the feature/enhancement

Hi.

Thank you for SlnParser.

When I try to parse a sln file which contains a solution configuration name other than "Debug" or "Release", I get the following exception:

```
SlnParser.Contracts.Exceptions.ParseSolutionFailedException: Could not parse provided Solution 'C:\Work\Team\dev\Test.sln'. See inner exception for more information ---> SlnParser.Contracts.Exceptions.UnexpectedSolutionStructureException: Default is not recognized as a possible value for BuildConfiguration

Stack Trace: 
SolutionConfigurationPlatformParser.ParseBuildConfiguration(String buildConfigurationString)
SolutionConfigurationPlatformParser.ParseConfigurationPlatformFromMatch(Match match)
SolutionConfigurationPlatformParser.ParseConfigurationPlatform(String line)
<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
SelectListIterator`2.ToList()
EnrichSolutionWithSolutionConfigurationPlatforms.Enrich(Solution solution, IEnumerable`1 fileContents)
SolutionParser.ParseInternal(FileInfo solutionFile)
SolutionParser.Parse(FileInfo solutionFile)
--- End of inner exception stack trace ---
SolutionParser.Parse(FileInfo solutionFile)
SolutionParser.Parse(String solutionFileName)
```

Solution configuration names can be anything (see below) and so I didn't expect `BuildConfiguration` to be an `enum`.

![image](https://github.com/wgnf/SlnParser/assets/507649/161b93b9-13d1-44f5-ace1-0d87c0df657a)

There's also a similar issue for `BuildPlatform`.
For example, `BuildPlatform` doesn't support `Mixed Platforms`, `Win32`, or any other custom name, and I didn't expect it to be an `enum` either.

![image](https://github.com/wgnf/SlnParser/assets/507649/ee386f84-7404-4364-bba1-53c184fc7931)

Instead, I expected those properties of `ConfigurationPlatform` to be of a `string` data type.

Thank you.

**Comment by wgnf** [comment]
Hi Rami,

thank you for bringing this to my attention.

You are right. Those values shouldn't be an enum. I'll have a look at this.

**Comment by wgnf** [comment]
Can you have a look at the following PR to make sure that the changes have the desired effect?
https://github.com/wgnf/SlnParser/pull/22
