### ISSUE TITLE
[FEAT]: Parse/Retrieve SolutionGuid

### ISSUE THREAD

**Issue by icnocop** [wgnf/SlnParser#23]
### Description of the feature/enhancement

Hi.

I would like to parse a solution file and be able to retrieve the `SolutionGuid`.

For example, given a Visual Studio solution file which contains content similar to the following:
https://github.com/wgnf/SlnParser/blob/ecb1f51f5fcfb326faaabad04cd2ed9684dac49f/src/SlnParser.Tests/Solutions/SlnParser.sln#L53-L55

I would like to get the `SolutionGuid` value as a `Guid` data type.
```
SolutionParser solutionParser = new SolutionParser();
ISolution solution = solutionParser.Parse(slnFilePath);
Guid solutionGuid = solution.Guid; // {7F92F20E-4C3D-4316-BF60-105559EFEAFF}
```

Thank you.

**Comment by icnocop** [comment]
I'm not sure if it should actually be a nullable Guid data type (ex. `Guid?`), in cases where the `SolutionGuid` doesn't exist.

**Comment by wgnf** [comment]
Hm. I would guess that every solution has a `Guid`, so I would declare it as non-nullable.  
  
Thank you for pointing this out though, seems like that this slipped through.

**Comment by wgnf** [comment]
Ok nvm, I found at least one solution in my stars that has no `SolutionGuid`, so I'll mark it as nullable
https://github.com/SteveSandersonMS/DotNetIsolator/blob/main/DotNetIsolator.sln
