### ISSUE TITLE
[BUG]: Support parsing solution configuration mappings for projects which don't have a platform

### ISSUE THREAD

**Issue by icnocop** [wgnf/SlnParser#24]
### Description of the feature/enhancement

Hi.

When trying to parse a solution file which contains an SQL Server Integration Services (SSIS) Project (i.e. `*.dtproj`), the following exception occurs:
```
SlnParser.Contracts.Exceptions.ParseSolutionFailedException: Could not parse provided Solution 'C:\Test\Test.sln'. See inner exception for more information
 ---> SlnParser.Contracts.Exceptions.UnexpectedSolutionStructureException: Expected to find ConfigurationPlatform but pattern did not match
```

`*.dtproj` files don't have the same XML schema as `*.csproj` or `*.vcxproj`, files for example, and only contain a project configuration name without a platform.

Here's an example sln file which contains a `*.dtproj`:  
https://github.com/Badrinarayanan-ah/Adhere-Health/blob/ab151354ce44ce87f2d87564b8acd34f526f62e0/DeathAndDisenrollment/DND.sln#L1-L21
```
﻿Microsoft Visual Studio Solution File, Format Version 10.00
# Visual Studio 2008
Project("{D183A3D8-5FD8-494B-B014-37F57B35E655}") = "DNDy", "DND\DeathAndDisenrollment.dtproj", "{D74B44EA-F09D-49F3-B0EF-CB159746A372}"
EndProject
Global
        GlobalSection(SolutionConfigurationPlatforms) = preSolution
                Development|Default = Development|Default
        EndGlobalSection
        GlobalSection(ProjectConfigurationPlatforms) = postSolution
                {D74B44EA-F09D-49F3-B0EF-CB159746A372}.Development|Default.ActiveCfg = Development
                {D74B44EA-F09D-49F3-B0EF-CB159746A372}.Development|Default.Build.0 = Development
        EndGlobalSection
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
        EndGlobalSection
        GlobalSection(SubversionScc) = preSolution
                Svn-Managed = True
                Manager = AnkhSVN - Subversion Support for Visual Studio
        EndGlobalSection
EndGlobal
```

The regular expression pattern https://github.com/wgnf/SlnParser/blob/ecb1f51f5fcfb326faaabad04cd2ed9684dac49f/src/SlnParser/Helper/SolutionConfigurationPlatformParser.cs#L55 will not match line 11 because it does not have a `|` after `= Development`.

Thank you.

**Comment by wgnf** [comment]
Okay thank you. I'll have a look at this in the coming days, probably not tomorrow though.
