### ISSUE TITLE
Licensing: You may want to consider switching to MIT from Unlicense

### ISSUE THREAD

**Issue by timabell** [wgnf/SlnParser#28]
Hello,

Just been reading up on licensing as I'm looking licenses for my derived projects. Turns out there are [a few issues with the Unlicense](https://softwareengineering.stackexchange.com/a/147120/48240).

It seems the [MIT license](https://choosealicense.com/licenses/mit/) is the closest in spirit to what you were intending so perhaps you'd consider switching to that? If you do let me know and I'll do the same for SlnEditor.

Tim

**Comment by wgnf** [comment]
Oh crap, thanks for pointing that out. I didn't even realize that.
Especially this point:

> is explicitly illegal in some places (Germany)

is quite important, because I'm from Germany and my company uses this too.

Thanks a lot!

**Comment by wgnf** [comment]
Switched to MIT license, see https://github.com/wgnf/SlnParser/commit/0c410d18930c9015a5ef39d66e6234479a7ce22a

**Comment by wgnf** [comment]
Also created a new release: https://github.com/wgnf/SlnParser/releases/tag/v4.0.0

**Comment by timabell** [comment]
You missed a bit :-) 

https://github.com/wgnf/SlnParser/blob/0c410d18930c9015a5ef39d66e6234479a7ce22a/src/SlnParser/SlnParser.csproj#L19

https://github.com/wgnf/SlnParser/blob/0c410d18930c9015a5ef39d66e6234479a7ce22a/README.md?plain=1#L4

**Comment by wgnf** [comment]
Damn, thanks 😅
